config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :searches, only: %i[new create] do
    resources :travels, only: :index do
      resources :liked_travels, only: :create
    end
  end

  resources :travels, only: %i[show new create] do
    resources :attendances, only: :create
    resources :messages, only: :create
    resources :attendances, only: :create do
      member do
        patch :accept
        patch :decline
      end
    end
    member do
      get :chatroom
    end
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  
  resources :users, only: :show
  resources :attendances, only: :update
  resources :conversations, only: :index

  get "/dashboard", to: "dashboard#dashboard"
  get "/dashboard/searches", to: "dashboard#my_searches"
  get "/dashboard/travels", to: "dashboard#my_travels"
  get "/dashboard/candidatures", to: "dashboard#my_candidatures"

  get "/fav/:id", to: "liked_travels#fav"
  get "/bookmarks", to: "liked_travels#bookmarks"
  resources :liked_travels, only: [:destroy]

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_travels

  def dashboard
  end

  def my_searches
    @searches = current_user.searches
  end

  def my_candidatures
    @my_attendances = current_user.attendances
  end

  def my_travels
  end

  private

  def set_travels
    @travels = Travel.where(user: current_user)
  end
end

app/views/dashboard/dashboard.html.erb
<div class="laurastylelike" style="z-index: -1;"></div>
<div class="container", style="padding: 22px">
  <div class="profile d-flex align-items-center", style="margin-bottom: 370px">
      <% if @current_user.photo.attached? %>
        <%= cl_image_tag @current_user.photo.key, class: "img-show rounded-circle", style:"width: 70px; height: 70px; margin-inline-start: 10px;"%>
      <% end %>
      <h1 style="margin-left: 21px; margin-top: 10px; font-family: 'Dela Gothic One', sans-serif; font-size: 32px"><strong> Tableau de bord</strong></h1>
  </div>

  <div class="dashboard-items">

    <%= link_to "/dashboard/searches", class: "w-100 h-100 link dashboard-item d-flex align-items-center p-3" do %>
      <h1 style="font-size: 24px">Mes recherches</h1>
      <i class='fas fa-chevron-right cream'></i>
    <% end %>

    <%= link_to "/dashboard/candidatures", class: "w-100 h-100 link dashboard-item d-flex align-items-center p-3" do %>
      <h1 style="font-size: 24px">Mes candidatures</h1>
      <i class='fas fa-chevron-right cream'></i>
    <% end %>

     <%= link_to "/dashboard/travels", class: "w-100 h-100 link dashboard-item d-flex align-items-center p-3", style:"border: 0px" do %>
      <h1 style="font-size: 24px">Mes voyages</h1>
      <i class='fas fa-chevron-right cream'></i>
    <% end %>

  </div>

</div>

<%= render "shared/navbar_dashboard" %>

app/views/dashboard/my_candidatures.html.erb
<div class="laurastylelike" style="z-index: -1;"></div>
<br>
<div style="text-align: center;">
  <i class="navbar-icone fa-solid fa-earth-americas fa-xl mt-4" style="font-size: 30px"></i>
  <h1 class="titre-candidatures" style="font-size: 22px">Mes candidatures</h1>
</div>

<% @my_attendances.each do |attendance| %>
  <div class="container mb-4 d-flex flex-column flex-wrap align-content-center">
    <%= link_to travel_path(attendance.travel, search_url: request.original_url) do %>
      <div class="mini-banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(18,51,47,0.3)), linear-gradient(rgba(18,51,47,0.3),rgba(18,51,47,0.3)), url('<%= cl_image_path attendance.travel.photo.key, crop: :fill %>')">

        <div class="card-infos">
          <div class="destinationcard mb-2">
            <%= attendance.travel.destination %>
          </div>


          <div class="goldtag-candidature"> Du <%= attendance.travel.start_date.strftime("%d/%m") %> au <%= attendance.travel.end_date.strftime("%d/%m") %> </div>
            <% if attendance.status == "confirmed" %>
              <div class="greentag-candidatures"> <%= attendance.translated_status %> </div>
              <% elsif attendance.status == "rejected" %>
              <div class="redtag-candidatures"> <%= attendance.translated_status %> </div>
              <% else %>
              <div class="orangetag-candidatures"> <%= attendance.translated_status %> </div>
              <% end %>

        </div>
      </div>
    <% end %>
  </div>
<% end %>

<%= render "shared/navbar_create_travel" %>

app/views/dashboard/my_searches.html.erb
<div class="recherches">
<h1>Mes recherches</h1>
 <% @searches.each do |search| %>
    <h2> <%= search.airport_start %></h2>
    <h2> <%= search.destination %></h2>
    <h2> <%= search.start_date %></h2>
    <% end %>
</div>

app/views/dashboard/my_travels.html.erb
<div>
  <h1>Mes voyages</h1>
</div>

<% @travels.each do |travel| %>
  <h1 class="text-white"><%= travel.destination %></h1>
  <div class="text-white">
    <% if travel.attendances.any? %>
      <% travel.attendances.each do |attendance| %>
        <p><%= attendance.status %> - <%= attendance.user.name %>
           <% if attendance.pending? %>
            <%= button_to 'Accepter', accept_travel_attendance_path(travel, attendance), method: :patch, class: "btn btn-success btn-sm" %>
            <%= button_to 'Refuser', decline_travel_attendance_path(travel, attendance), method: :patch, class: "btn btn-danger btn-sm" %>
          <% elsif attendance.confirmed? %>
            <span class="badge bg-success">Accepté</span>
          <% elsif attendance.rejected? %>
            <span class="badge bg-danger">Refusé</span>
          <% end %>
        </p>
      <% end %>
    <% else %>
      <p>Pas encore de candidature pour ce voyage</p>
    <% end %>
  </div>
<% end %>