config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :searches, only: %i[new create] do
    resources :travels, only: :index do
      resources :liked_travels, only: :create
    end
  end

  resources :travels, only: %i[show new create] do
    resources :attendances, only: :create
    resources :messages, only: :create
    resources :attendances, only: :create do
      member do
        patch :accept
        patch :decline
      end
    end
    member do
      get :chatroom
    end
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  
  resources :users, only: :show
  resources :attendances, only: :update
  resources :conversations, only: :index

  get "/dashboard", to: "dashboard#dashboard"
  get "/dashboard/searches", to: "dashboard#my_searches"
  get "/dashboard/travels", to: "dashboard#my_travels"
  get "/dashboard/candidatures", to: "dashboard#my_candidatures"

  get "/fav/:id", to: "liked_travels#fav"
  get "/bookmarks", to: "liked_travels#bookmarks"
  resources :liked_travels, only: [:destroy]

end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :user

  has_one_attached :photo
  has_many :messages, dependent: :destroy
  has_many :attendances, dependent: :destroy

  MOODS = ["Sport", "Culture", "Détente", "Aventure"]

  validates :airport_start, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :budget_max, presence: true
  validates :destination, presence: true
  validates :mood, presence: true
  validates :age, presence: true

  after_create :create_attendance

  def user_has_attended?(user)
    attendances.exists?(user: user)
  end

  def create_attendance
    self.attendances.create(user: self.user)
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  def index
    @search = Search.find(params[:search_id])
    @travels = Travel.all

    @travels = @travels.where(airport_start: @search.airport_start) if @search.airport_start.present?

    if @search.start_date.present? && @search.end_date.present?
      @travels = @travels.where("start_date >= ? AND end_date <= ?", @search.start_date, @search.end_date)
    elsif @search.start_date.present?
      @travels = @travels.where("start_date >= ?", @search.start_date)
    elsif @search.end_date.present?
      @travels = @travels.where("end_date <= ?", @search.end_date)
    end

    @travels = @travels.where(budget_max: @search.budget_max) if @search.budget_max.present?
    @travels = @travels.where(destination: @search.destination) if @search.destination.present?
    @travels = @travels.where(mood: @search.mood) if @search.mood.present?
    @travels = @travels.where(age: @search.age) if @search.age.present?

    if @travels.empty?
      flash.now[:notice] = "Aucun voyage ne correspond à votre recherche. #{view_context.link_to('Revenir à la page de recherche', new_search_path)}".html_safe
    end
  end

  def new
    @travel = Travel.new
  end

  def create
    @travel = Travel.new(travel_params)
    @travel.user = current_user
    if @travel.save
      redirect_to travel_path(@travel)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @travel = Travel.find(params[:id])
    @search_url = params[:search_url]
  end

  def chatroom
    @travel = Travel.find(params[:id])
    @message = Message.new
  end

  private

  def travel_params
    params.require(:travel).permit(:airport_start, :start_date, :end_date, :budget_max, :destination, :mood, :age, :status, :date_range)
  end
end

app/views/travels/_participants.html.erb
 <h1 class="fs-6 mb-4" style="color: #F5EADD;  font-family: 'Dela Gothic One', sans-serif; line-height: 150%;">Découvrez les autres voyageurs</h1>
  <% @travel.attendances.confirmed.each do |attendance| %>
    <%= link_to user_path(attendance.user, search_url: request.original_url), class:"lien" do %>
      <div class="carditem">
        <div style="color: #F5EADD;  font-family: 'Dela Gothic One', sans-serif">
          <%= cl_image_tag attendance.user.photo.key, class: "carditem-avatar me-2", alt: "dropdown menu" %>
          <%= attendance.user.name %>
        </div>
        <i class="fa-solid fa-chevron-right"></i>
      </div>
    <% end %>
  <% end %>

app/views/travels/_programme.html.erb
  <div class="d-flex flex-wrap mb-3">
    <div class="goldtag"> Du <%= @travel.start_date.strftime("%d/%m") %> au <%= @travel.end_date.strftime("%d/%m") %> </div>
    <div class="goldtag"> Départ - <%= @travel.airport_start %> </div>
    <div class="goldtag"> Budget max - <%= @travel.budget_max %> € </div>
    <div class="goldtag"><%= @travel.mood %> </div>
  </div>

  <h1 class="fs-5" style="color: #F5EADD;  font-family: 'Dela Gothic One', sans-serif">Au programme</h1>
  <div style="color: #F5EADD" ><%= @travel.description %></div>

app/views/travels/_travel.html.erb
<div class="container d-flex justify-content-center pb-4">
<%= link_to travel_path(travel, search_url: request.original_url) do %>
      <% if travel.photo.attached? %>
        <div id="favcard" class="banner half-width" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(18,51,47,0.3)), linear-gradient(rgba(18,51,47,0.3),rgba(18,51,47,0.3)), url('<%= cl_image_path travel.photo.key, crop: :fill %>')">
      <% else %>
        <div id="favcard" class="banner half-width" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(18,51,47,0.3)), linear-gradient(rgba(18,51,47,0.3),rgba(18,51,47,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
      <% end %>
        <div class="user-profile d-flex">
          <% if travel.user.photo.attached? %>
            <%= cl_image_tag travel.user.photo.key, class: "card-trip-user avatar-bordered me-2", alt: "dropdown menu" %>
          <% else %>
            <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered me-2" />
          <% end %>
          <div class="entete">
          <h6><%= travel.user.name %></h6>
          </div>
        </div>

        <div class="card-infos">
          <div class="destinationcard mb-2">
            <%= travel.destination %>
          </div>

          <div class="card-details d-flex mb-3">
            <div class="goldtag"> Du <%= travel.start_date.strftime("%d/%m") %> au <%= travel.end_date.strftime("%d/%m") %> </div>
            <div class="d-flex">
              <div class="goldtag"><%= travel.budget_max %> € </div>
              <div class="goldtag"><%= travel.mood %> </div>
            </div>
          </div>
        </div>
  <% end %>

  <% if LikedTravel.find_by(travel: travel) %>
  <i id="favbutton" class="fa-solid fa-heart" data-controller="like-travels" data-action="click->like-travels#liked" data-like-travels-id-value="<%= travel.id%>" data-like-travels-search-value="<%= params[:search_id]%>"></i>
  <% else %>
  <i id="favbutton" class="fa-regular fa-heart" data-controller="like-travels" data-action="click->like-travels#liked" data-like-travels-id-value="<%= travel.id%>" data-like-travels-search-value="<%= params[:search_id]%>"></i>
  <% end %>
  </div>
</div>

app/views/travels/chatroom.html.erb
<div class="container chatroom"
  data-controller="travel-subscription"
  data-travel-subscription-travel-id-value="<%= @travel.id %>"
  data-travel-subscription-current-user-id-value="<%= current_user.id %>">

  <h1 style="color: #1B3232"><%= cl_image_tag @travel.photo.key, class: "card-trip-user avatar-bordered me-2" %> <%= @travel.destination %></h1>
  <div class="d-flex justify-content-center pb-1 avatars-overlap">
    <p><% @travel.attendances.uniq.each do |attendance| %>
      <span class="avatar-overlap">
        <%= cl_image_tag attendance.user.photo.key, class: "card-trip-user avatar-bordered me-2"  %>
      </span>
    <% end %></p>
  </div>



  <div class="messages" data-travel-subscription-target="messages">
    <% @travel.messages.each do |message| %>
      <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
        <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
          <%= render "messages/message", message: message %>
        </div>
      </div>
    <% end %>
  </div>

  <%= simple_form_for [@travel, @message],
    html: { data: { action: "turbo:submit-end->travel-subscription#resetForm" }, class: "d-flex" } do |f| %>
    <%= f.input :content,
      label: false,
      placeholder: "Message dans #{@travel.destination} ",
      wrapper_html: { class: "flex-grow-1" },
      input_html: { class: "chatroom-input"}
    %>
    <%= button_tag(type: 'submit', class: 'btn-submit') do %>
      <i class="fa-regular fa-paper-plane"></i>
    <% end %>
  <% end %>
</div>

<%= render "shared/navbar_messages" %>

app/views/travels/index.html.erb
<div class="pb-5">
<div class="laurastyleup" style="z-index: -1;"></div>
  <div class="d-flex flex-column align-content-center ps-5 pe-5 pt-5 pb-3" style="position: relative; z-index: 1;" >
  <%= link_to "Modifier ma recherche", new_search_path, class: "btn btn-secondary rounded-5 mb-4", style: 'color: #F5EADD; background-color: #1B3232; font-family:"Nunito", "Helvetica", "sans-serif"; font-weight: 500' %>
    <p class="align-self-center h4" style='color: #F5EADD;  font-family: "Dela Gothic One", sans-serif'>Découvre les voyages proposés</p>
  </div>
   <%= render @travels %>
  </div>

<%= render "shared/navbar_search" %>

app/views/travels/new.html.erb
<div class="container pb-5">

  <h1 class="title-searches">Quel voyage voulez-vous partager ?</h1>
  <%= simple_form_for @travel do |f| %>
    <%= f.input :airport_start, placeholder: 'Aéroport de départ', label:false %>
    <%= f.input :destination, placeholder: 'Destination', label:false %>

    <div class="form-group">
      <%= f.input :start_date, html5: true, input_html: { value: params.dig(:search, :start_date) || Date.today}, placeholder: 'Date de départ', label:'Date de départ' %>
      <%= f.input :end_date, html5: true, input_html: { value: params.dig(:search, :end_date)  || Date.tomorrow + 2.month + 10.days }, placeholder: "Date d'arrivée", label: "Date d'arrivée" %>

    </div>

    <%= f.input :budget_max, placeholder: 'Ton budget max', label:false %>
    <%# <%= f.input :mood, collection: Travel::MOODS, label:false, prompt: 'Choisissez votre mood'%>
    <%= f.input :mood, collection: Travel::MOODS, label:"Choisis ton mood", as: :radio_buttons, input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item', include_hidden: false, multiple: false %>
    <%= f.input :age, placeholder: 'Ton âge', label:false %>
    <%= f.submit "Ajouter un voyage !", class: "btn-search" %>
  <% end %>
</div>
<%= render "shared/navbar_create_travel" %>

app/views/travels/show.html.erb
<div class="container-show-user", style="background-image: linear-gradient(0deg, rgba(27,50,50,1) 1%, rgba(27,50,50,0.7) 80%), url('<%= cl_image_path @travel.photo.key %>');">
  <div class="btn-retour">
    <%= link_to @search_url do %>
      <i class="fa-solid fa-arrow-left fa-xl p-3" style="position: absolute; top: 10px; left: 0; color: #fde8d0;"></i>
    <% end %>
  </div>

  <h1 class="destination mt-5 mb-4" style="font-size: 250%;"><%= @travel.destination %></h1>
  <div class="soustitre mt-5", style="font-size: medium">proposé par</div>

    <%= link_to user_path(@travel.user, search_url: request.original_url), class:"lien", style:"width: 90vw" do %>
      <div class="carditem mb-4", style="background-color: #244444">
        <div class="d-flex", style="color: #F5EADD; font-family: 'Dela Gothic One', sans-serif">
          <%= cl_image_tag @travel.user.photo.key, style:"width: 55px; height: 55px !important" , class: "carditem-avatar me-2", alt: "dropdown menu" %>
          <div style="font-size: x-large; line-height: 1.25; align-self: center;">
            <%= @travel.user.name %>
            <div class="soustitre" style="font-size: medium;"><%= @travel.user.age %> ans</div>
          </div>
        </div>
        <i class="fa-solid fa-chevron-right"></i>
      </div>
    <% end %>
</div>

<div class="show-user-description px-3">
  <% if @travel.user_has_attended?(current_user) && @travel.attendances.find_by(user: current_user).status == "confirmed"%>
    <div class="col-12">
      <%= link_to "Discussion de groupe", chatroom_travel_path(@travel), class: "btn btn-candidate rounded-5 w-100 mb-4" %>
    </div>
  <% else %>
    <div class="justify-content-around row mb-5">
      <div class="col-6">
          <%= link_to "Contacter", chatroom_path(current_user.chatroom(@travel.user)), class: "btn btn-candidate rounded-5 w-100" %>
      </div>
      <div class="col-6">
          <% if @travel.user_has_attended?(current_user) == false %>
            <%= form_with(model: [@travel, Attendance.new], local: true) do |form| %>
              <%= form.hidden_field :user_id, value: current_user.id %>
              <%= form.submit 'Candidater', class: "btn btn-candidate rounded-5 w-100" %>
            <% end %>
          <% else %>
            <button type="button" class="btn btn-secondary rounded-5 w-100" disabled>Déjà candidaté</button>
          <% end %>
      </div>
    </div>
  <% end %>

    <div data-controller="switch">
      <div class="d-flex">
        <div data-action="click->switch#programme" data-switch-target="onglet1" class="selectedpartial ">Détails</div>
        <div data-action="click->switch#participants" data-switch-target="onglet2"class="unselectedpartial">Participants</div>
      </div>
      <div data-switch-target="programme" class="backgroundpartial"><%= render "programme" %></div>
      <div data-switch-target="participants" class="d-none backgroundpartial"><%= render "participants" %></div>
    </div>
</div>

<%= render "shared/navbar_search" %>