config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :searches, only: %i[new create] do
    resources :travels, only: :index do
      resources :liked_travels, only: :create
    end
  end

  resources :travels, only: %i[show new create] do
    resources :attendances, only: :create
    resources :messages, only: :create
    resources :attendances, only: :create do
      member do
        patch :accept
        patch :decline
      end
    end
    member do
      get :chatroom
    end
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  
  resources :users, only: :show
  resources :attendances, only: :update
  resources :conversations, only: :index

  get "/dashboard", to: "dashboard#dashboard"
  get "/dashboard/searches", to: "dashboard#my_searches"
  get "/dashboard/travels", to: "dashboard#my_travels"
  get "/dashboard/candidatures", to: "dashboard#my_candidatures"

  get "/fav/:id", to: "liked_travels#fav"
  get "/bookmarks", to: "liked_travels#bookmarks"
  resources :liked_travels, only: [:destroy]

end

app/models/liked_travel.rb
class LikedTravel < ApplicationRecord
  belongs_to :search
  belongs_to :travel
end

app/controllers/liked_travels_controller.rb
class LikedTravelsController < ApplicationController

  def fav
    @travel = Travel.find(params[:id])
    @search = Search.find(params[:search])

    if LikedTravel.find_by(travel: @travel)
      LikedTravel.find_by(travel: @travel).destroy
    else
      LikedTravel.create(travel: @travel, search: @search)
    end

    render json: { status: "ok" }
  end

  def bookmarks
    @liked_travels = current_user.liked_travels
    @search_url = :bookmarks_url
  end

  def show
  end

  def destroy
    @liked_travel = LikedTravel.find(params[:id])
    @liked_travel.destroy
    redirect_to bookmarks_path, status: :see_other
  end
end

app/views/liked_travels/bookmarks.html.erb
<div class="pb-5">
  <div class="laurastylelike" style="z-index: -1;"></div>
  <div class="d-flex flex-column align-content-center mb-4" >
    <i class="fa-regular fa-heart fa-2xl p-4 mt-4 mb-1 align-self-center" style="color: #D6A266"></i>
    <p class="align-self-center h4" style='color: #F5EADD;  font-family: "Dela Gothic One", sans-serif'>Mes coups de coeur</p>
  </div>



  <% @liked_travels.each do |liked_travel| %>
    <div class="container mb-4 d-flex flex-column flex-wrap align-content-center">
        <%= link_to travel_path(liked_travel.travel, search_url: request.original_url) do %>
        <div class="banner half-width" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(18,51,47,0.3)), linear-gradient(rgba(18,51,47,0.3),rgba(18,51,47,0.3)), url('<%= cl_image_path liked_travel.travel.photo.key, crop: :fill %>')">
            <div class="user-profile d-flex">
              <%= cl_image_tag liked_travel.travel.user.photo.key, class: "card-trip-user avatar-bordered me-2", alt: "dropdown menu" %>
              <div class="entete">
              <h6><%= liked_travel.travel.user.name %></h6>
              <div class="soustitre">propose</div>
              </div>
            </div>

            <div class="card-infos">
              <div class="destinationcard mb-2">
                <%= liked_travel.travel.destination %>
              </div>

              <div class="card-details d-flex mb-3 ">
                <div class="goldtag"> Du <%= liked_travel.travel.start_date.strftime("%d/%m") %> au <%= liked_travel.travel.end_date.strftime("%d/%m") %> </div>
                <div class="d-flex">
                  <div class="goldtag"><%= liked_travel.travel.budget_max %> € </div>
                  <div class="goldtag"><%= liked_travel.travel.mood %> </div>
                </div>
              </div>
            </div>
          </div>
          <%= link_to liked_travel_path(liked_travel), data: { turbo_method: :delete } do %>
          <i id="favbutton" class="fa-solid fa-trash pe-4"></i>
          <% end %>
        <% end %>
    </div>
  <% end %>
</div>



<%= render "shared/navbar_bookmarks" %>