config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :searches, only: %i[new create] do
    resources :travels, only: :index do
      resources :liked_travels, only: :create
    end
  end

  resources :travels, only: %i[show new create] do
    resources :attendances, only: :create
    resources :messages, only: :create
    resources :attendances, only: :create do
      member do
        patch :accept
        patch :decline
      end
    end
    member do
      get :chatroom
    end
  end

  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
  
  resources :users, only: :show
  resources :attendances, only: :update
  resources :conversations, only: :index

  get "/dashboard", to: "dashboard#dashboard"
  get "/dashboard/searches", to: "dashboard#my_searches"
  get "/dashboard/travels", to: "dashboard#my_travels"
  get "/dashboard/candidatures", to: "dashboard#my_candidatures"

  get "/fav/:id", to: "liked_travels#fav"
  get "/bookmarks", to: "liked_travels#bookmarks"
  resources :liked_travels, only: [:destroy]

end

app/views/shared/_card.html.erb
<div id="travelCarousel" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <% Travel.all.each_with_index do |travel, index| %>
      <div class="carousel-item <%= 'active' if index == 0 %>">
        <div class="d-flex justify-content-center">
        <%= link_to travel_path(travel, search_url: request.original_url) do %>
          <% if travel.photo.attached? %>
            <div class="banner half-width" style="width: 69vw; background-image: linear-gradient(rgba(0,0,0,0.2),rgba(18,51,47,0.3)), linear-gradient(rgba(18,51,47,0.3),rgba(18,51,47,0.3)), url('<%= cl_image_path travel.photo.key, crop: :fill %>')">
          <% else %>
            <div class="banner half-width" style="width: 69vw; background-image: linear-gradient(rgba(0,0,0,0.2),rgba(18,51,47,0.3)), linear-gradient(rgba(18,51,47,0.3),rgba(18,51,47,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
          <% end %>
            <div class="user-profile d-flex">
                <% if travel.user.photo.attached? %>
                  <%= cl_image_tag travel.user.photo.key, class: "card-trip-user avatar-bordered me-2", alt: "dropdown menu" %>
                <% else %>
                  <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered me-2" />
                <% end %>
             <div class="entete">
                <h6><%= travel.user.name %></h6>
                <div class="soustitre">propose</div>
              </div>
            </div>

            <div class="card-infos">
             <div class="destinationcard mb-2">
                <%= travel.destination %>
              </div>

               <div class="card-details d-flex mb-3">
                  <div class="goldtag"> Du <%= travel.start_date.strftime("%d/%m") %> au <%= travel.end_date.strftime("%d/%m") %> </div>
                  <div class="d-flex">
                    <div class="goldtag"><%= travel.budget_max %> € </div>
                    <div class="goldtag"><%= travel.mood %> </div>
                  </div>
                </div>
            </div>
          </div>
        <% end %>
      </div>
     </div>
    <% end %>
  </div>
  <!-- Add Controls -->
  <button class="carousel-control-prev" type="button" data-bs-target="#travelCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#travelCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", conversations_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Mon profil", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_bookmarks.html.erb
<nav class="nav-containerheart">

  <!-- menu items -->
  <%= link_to root_path do %>
    <i class="navbar-icone fa-solid fa-magnifying-glass fa-xl ms-1"></i>
  <% end %>

  <%= link_to bookmarks_path do %>
    <i class="navbar-selectedheart fa-regular fa-heart fa-xl"></i>
  <% end %>

  <%= link_to dashboard_candidatures_path do %>
    <i class="navbar-icone fa-solid fa-earth-americas fa-xl"></i>
  <% end %>

 <%= link_to conversations_path do %>
    <i class="navbar-icone fa-regular fa-message fa-xl"></i>
  <% end %>

  <%= link_to dashboard_path do %>
    <i class="navbar-icone fa-regular fa-user fa-xl me-1"></i>
  <% end %>
</nav>

app/views/shared/_navbar_create_travel.html.erb
<nav class="nav-containerheart">

  <!-- menu items -->
  <%= link_to root_path do %>
    <i class="navbar-icone fa-solid fa-magnifying-glass fa-xl ms-1"></i>
  <% end %>

  <%= link_to bookmarks_path do %>
    <i class="navbar-icone fa-regular fa-heart fa-xl"></i>
  <% end %>

<%= link_to dashboard_candidatures_path do %>
    <i class="navbar-selectedheart fa-solid fa-earth-americas fa-xl"></i>
  <% end %>

  <%= link_to conversations_path do %>
    <i class="navbar-icone fa-regular fa-message fa-xl"></i>
  <% end %>

  <%= link_to dashboard_path do %>
    <i class="navbar-icone fa-regular fa-user fa-xl me-1"></i>
  <% end %>
</nav>

app/views/shared/_navbar_dashboard.html.erb
<nav class="nav-container">

  <!-- menu items -->
  <%= link_to root_path do %>
    <i class="navbar-icone fa-solid fa-magnifying-glass fa-xl ms-1"></i>
  <% end %>

  <%= link_to bookmarks_path do %>
    <i class="navbar-icone fa-regular fa-heart fa-xl"></i>
  <% end %>

  <%= link_to dashboard_candidatures_path do %>
    <i class="navbar-icone fa-solid fa-earth-americas fa-xl"></i>
  <% end %>

  <%= link_to conversations_path do %>
    <i class="navbar-icone fa-regular fa-message fa-xl"></i>
  <% end %>

  <%= link_to dashboard_path, class: "me-1" do %>
    <i class="navbar-icone fa-regular fa-user fa-xl"></i>
  <% end %>
</nav>

app/views/shared/_navbar_message.html.erb
<nav class="nav-containerheart">

  <!-- menu items -->
  <%= link_to root_path do %>
    <i class="navbar-icone fa-solid fa-magnifying-glass fa-xl ms-1"></i>
  <% end %>

  <%= link_to bookmarks_path do %>
    <i class="navbar-icone fa-regular fa-heart fa-xl"></i>
  <% end %>

  <%= link_to dashboard_candidatures_path do %>
    <i class="navbar-icone fa-solid fa-earth-americas fa-xl"></i>
  <% end %>

  <%= link_to root_path do %>
    <i class="navbar-selectedheart fa-regular fa-message fa-xl"></i>
  <% end %>

  <%= link_to dashboard_path do %>
    <i class="navbar-icone fa-regular fa-user fa-xl me-1"></i>
  <% end %>
</nav>

app/views/shared/_navbar_messages.html.erb
<nav class="nav-containerfull">

  <!-- menu items -->
  <%= link_to root_path do %>
    <i class="navbar-icone fa-solid fa-magnifying-glass fa-xl ms-1"></i>
  <% end %>

  <%= link_to bookmarks_path do %>
    <i class="navbar-icone fa-regular fa-heart fa-xl"></i>
  <% end %>

  <%= link_to dashboard_candidatures_path do %>
    <i class="navbar-icone fa-solid fa-earth-americas fa-xl"></i>
  <% end %>

 <%= link_to conversations_path do %>
    <i class="navbar-selected fa-regular fa-message fa-xl"></i>
  <% end %>

  <%= link_to dashboard_path do %>
    <i class="navbar-icone fa-regular fa-user fa-xl me-1"></i>
  <% end %>
</nav>

app/views/shared/_navbar_search.html.erb
<nav class="nav-containerfull">

  <!-- menu items -->
  <%= link_to root_path, class: "ms-1" do %>
    <i class="navbar-selected fa-solid fa-magnifying-glass fa-xl"></i>
  <% end %>

  <%= link_to bookmarks_path do %>
    <i class="navbar-icone fa-regular fa-heart fa-xl"></i>
  <% end %>

  <%= link_to dashboard_candidatures_path do %>
    <i class="navbar-icone fa-solid fa-earth-americas fa-xl"></i>
  <% end %>

  <%= link_to conversations_path do %>
    <i class="navbar-icone fa-regular fa-message fa-xl"></i>
  <% end %>

  <%= link_to dashboard_path do %>
    <i class="navbar-icone fa-regular fa-user fa-xl me-1"></i>
  <% end %>
</nav>